packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  prisma: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@expo/cli@57.0.11'
  - '@expo/inline-modules@0.1.4'
  - '@expo/local-build-cache-provider@57.0.5'
  - '@expo/log-box@57.0.2'
  - '@expo/metro-runtime@57.0.8'
  - '@expo/prebuild-config@57.0.10'
  - '@expo/ui@57.0.8'
  - babel-preset-expo@57.0.5
  - expo-asset@57.0.8
  - expo-constants@57.0.8
  - expo-modules-core@57.0.8
  - expo-router@57.0.9
  - expo-system-ui@57.0.2
  - expo@57.0.9
  - eslint-config-expo@57.0.1
  - jest-expo@57.0.3
  - expo-dev-client@57.0.11
  - expo-dev-launcher@57.0.11
  - expo-dev-menu@57.0.11
  - expo-updates@57.0.13
